import type { Metadata } from "next";
import { Syne, Rubik } from "next/font/google";
import "../globals.css";
import RootProvider from "@/provider/RootProvider";

const syne = Syne({
  variable: "----font-syne",
  subsets: ["latin"],
  display: "swap",
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${syne.variable} ${rubik.variable} antialiased`}
    >
      <body suppressHydrationWarning>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
